### ISSUE TITLE
Implement on-the-fly generation for encryption

### ISSUE THREAD

**Issue by pontus** [elixir-oslo/crypt4gh#7]
The python implementation supports generating a private key for encryption on the fly (when signing is not part of the use case), which simplifies things for users.

Could that be implemented in this codebase as well?

**Comment by dtitov** [comment]
It is possible. Do you want me to add such a method to the API?

**Comment by pontus** [comment]
Yes, please, if it does not involve unreasonable amounts of work. 

(The ability to encrypt without setting up a private key of ones own made us pick the python implementation for our first use case, but it would be simpler with this code base, I think.)
